name: Ru-C_Design
channels:
  - defaults
  - openbabel
  - rdkit
  - anaconda
  - conda-forge
dependencies:
  - openbabel
  - openjdk=8.0.152
  - jupyterlab
  - ipykernel
  - rdkit
  - matplotlib
  - scipy
  - scikit-learn
  - svgutils
